version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: next_blog_app
      MYSQL_USER: kensuke
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: